version: '3.9'
services:
        server:
                build:
                        context: .
                        dockerfile: ./Dockerfile
                ports:
                        - 3000:3000
                container_name: ysapp
                image: ysapp:latest
                tty: true
                stdin_open: true
                command: bundle exec rails s -p 3000 -b '0.0.0.0'
